### ISSUE TITLE
BSON MaxSize error in some ExerciseStudentProgress... too long docuement

### ISSUE THREAD

**Issue by fedescarpa** [mumuki/mumuki-classroom-api#91]
Some documents are too big and we are missing some solutions

**Comment by fedescarpa** [comment]
The student who has 16MB BSON document sent 1019 submissions for one exercise. I think this probably won't happen again, so this isn't priority.

![bitmoji](https://render.bitstrips.com/v2/cpanel/10216849-170770054_3-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by flbulgarelli** [comment]
I agree. This is not an issue.
