### ISSUE TITLE
Wrong login methods format

### ISSUE THREAD

**Issue by aguspina** [mumuki/mumuki-classroom-api#97]
Nowadays classroom is expecting organization data to be like this
```json
{
  "name": "organization",
  "lock_json": {
    "connections": ["facebook", "user_pass"]
  }
}
```

But `office` is sending data like this 
```json
{
  "login_methods": ["facebook", "user_pass"]
}
```

This difference throw an internal server error in some organizations.

**Comment by aguspina** [comment]
I made a quickfix, but the best way is to unify the data

**Comment by julian-berbel** [comment]
I believe this was fixed when we unified login :thinking: @luchotc

**Comment by luchotc** [comment]
Yep! Nice @julian-berbel
